services:
  - docker

before_install:
   - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERUSER" --password-stdin
   - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" quay.io

env:
  - export DOCKER_CLI_EXPERIMENTAL=enabled

jobs:
  include:
   - stage: Build amd64 container image
     name: building amd64 image
     arch: amd64
     os: linux
     script:
       - make docker-build
       - make docker-tag
       - make docker-push

   - stage: Build ppc64le container image
     name: building ppc64le image
     arch: ppc64le
     os: linux
     script:
       - make docker-build
       - make docker-tag
       - make docker-push
       - make manifest-create
       - make manifest-push
